# -*- coding: utf-8 -*-
"""Question_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3iUwpxlinwdmYU68Of9E8VJ8PnLpMPE
"""

import numpy as np

# ── Problem Parameters ───────────────────────────────────────────────────────
# Example instance (adjustable)
N = 4                          # number of plants
Q = 10                         # total water available (small for demonstration)
W0 = 0.1 * Q                  # initial upstream waste = 0.1Q

# Waste produced per unit of water consumed at each plant
a = {1: 0.5, 2: 0.3, 3: 0.4, 4: 0.2}

# Cost function c_n(q * w) — example: quadratic form c_n(z) = alpha_n * z
# You can change these to any function of z = q * w
alpha = {1: 2.0, 2: 3.0, 3: 1.5, 4: 2.5}

def cost_fn(n, q, w):
    """Cost at plant n for consuming q water with upstream waste w."""
    z = q * w
    return alpha[n] * z    # linear in z; change to any c_n(z) as needed

# ── Discretization ───────────────────────────────────────────────────────────
# Discretize water into integer units for DP
water_step = 1                 # granularity (1 unit)
water_levels = list(range(0, Q + 1, water_step))
num_water = len(water_levels)

# Waste is continuous but determined by decisions, so we track it exactly
# We use a dictionary-based DP: f[n][(s, w_rounded)] = min cost

INF = float('inf')
ROUND_DIGITS = 4  # rounding for waste keys to avoid float issues

def rkey(w):
    return round(w, ROUND_DIGITS)

# ── DP Tables ────────────────────────────────────────────────────────────────
# f[n][(s, w)] = min cost from plant n onwards with s water remaining, w upstream waste
# policy[n][(s, w)] = optimal q_n

f = {n: {} for n in range(1, N + 2)}
policy = {n: {} for n in range(1, N + 1)}

# ── Terminal Condition ───────────────────────────────────────────────────────
# After plant N, no more cost
# We'll build these dynamically during backward induction

# ── Forward-pass to enumerate reachable states ───────────────────────────────
# Since waste depends on the path, we enumerate reachable (s, w) pairs
# at each stage via a forward pass of all possible allocations

reachable = {n: set() for n in range(1, N + 2)}
reachable[1].add((Q, rkey(W0)))

for n in range(1, N + 1):
    for (s, w) in reachable[n]:
        for q in range(0, s + 1, water_step):
            s_next = s - q
            w_next = rkey(w + a[n] * q)
            reachable[n + 1].add((s_next, w_next))

print("=" * 70)
print("  WELADARE RIVER WATER ALLOCATION — DP SOLUTION")
print("=" * 70)
print(f"\n  Plants: {N}")
print(f"  Total water: Q = {Q}")
print(f"  Initial waste: 0.1Q = {W0}")
print(f"  Waste rates a_n: {a}")
print(f"  Cost coefficients alpha_n: {alpha}")
print(f"  Cost function: c_n(q, w) = alpha_n * (q * w)")
print(f"\n  Reachable states per stage:")
for n in range(1, N + 2):
    print(f"    Stage {n}: {len(reachable[n])} states")

# ── Terminal condition ────────────────────────────────────────────────────────
# All water must be consumed: only s=0 is feasible at the end
for (s, w) in reachable[N + 1]:
    if s == 0:
        f[N + 1][(s, w)] = 0.0
    else:
        f[N + 1][(s, w)] = INF  # infeasible: water left over

# ── Backward Induction ───────────────────────────────────────────────────────
for n in range(N, 0, -1):
    print(f"\n  Solving Stage {n} (Plant {n})...")
    for (s, w) in reachable[n]:
        best_cost = INF
        best_q = None

        for q in range(0, s + 1, water_step):
            s_next = s - q
            w_next = rkey(w + a[n] * q)

            future = f[n + 1].get((s_next, w_next), INF)
            if future == INF:
                continue

            immediate = cost_fn(n, q, w)
            total = immediate + future

            if total < best_cost:
                best_cost = total
                best_q = q

        f[n][(s, w)] = best_cost
        policy[n][(s, w)] = best_q

# ── Optimal Solution ─────────────────────────────────────────────────────────
print()
print("=" * 70)
print("  OPTIMAL SOLUTION")
print("=" * 70)

opt_cost = f[1][(Q, rkey(W0))]
print(f"\n  Minimum total regional cost: {opt_cost:.2f}")

# Trace optimal path
s = Q
w = rkey(W0)
total_cost = 0
results = []

for n in range(1, N + 1):
    q = policy[n][(s, w)]
    immediate = cost_fn(n, q, w)
    total_cost += immediate
    s_next = s - q
    w_next = rkey(w + a[n] * q)

    results.append({
        "Plant": n,
        "Water Remaining (s)": s,
        "Upstream Waste (w)": round(w, 2),
        "Water Allocated (q)": q,
        "Waste Added (a_n*q)": round(a[n] * q, 2),
        "Cost c_n(q*w)": round(immediate, 2),
        "Cumulative Cost": round(total_cost, 2),
        "Next Water": s_next,
        "Next Waste": round(w_next, 2),
    })

    s = s_next
    w = w_next

# Print results table
print(f"\n  {'Plant':>5} {'Water(s)':>9} {'Waste(w)':>9} {'Alloc(q)':>9} "
      f"{'Added':>8} {'Cost':>10} {'Cumul':>10}")
print(f"  {'-'*65}")
for r in results:
    print(f"  {r['Plant']:>5} {r['Water Remaining (s)']:>9} {r['Upstream Waste (w)']:>9.2f} "
          f"{r['Water Allocated (q)']:>9} {r['Waste Added (a_n*q)']:>8.2f} "
          f"{r['Cost c_n(q*w)']:>10.2f} {r['Cumulative Cost']:>10.2f}")

print(f"\n  Water unused: {s}")
print(f"  Final waste level: {w:.2f}")

# ── Detailed DP table for small problems ──────────────────────────────────────
if Q <= 20:
    print()
    print("=" * 70)
    print("  DETAILED DP TABLE (small instance)")
    print("=" * 70)
    for n in range(N, 0, -1):
        print(f"\n  Stage {n} — Plant {n}:")
        print(f"  {'s':>5} {'w':>8} {'f_'+str(n)+'(s,w)':>12} {'q*':>5}")
        print(f"  {'-'*35}")
        sorted_states = sorted(reachable[n], key=lambda x: (x[0], x[1]))
        for (s, w) in sorted_states:
            val = f[n].get((s, w), INF)
            q = policy[n].get((s, w), '-')
            if val < INF:
                print(f"  {s:>5} {w:>8.2f} {val:>12.2f} {q:>5}")

# ── Sensitivity: show how allocation changes with different waste rates ──────
print()
print("=" * 70)
print("  VERIFICATION")
print("=" * 70)
print(f"\n  Optimal cost from DP:  {opt_cost:.2f}")
print(f"  Sum of stage costs:    {sum(r['Cost c_n(q*w)'] for r in results):.2f}")
print(f"  Match: {abs(opt_cost - sum(r['Cost c_n(q*w)'] for r in results)) < 0.01}")

